version: 1

page_update_date: today

maps:
- in: HGPS_Significance_0.1deg.fits.gz
  quantity: significance
  radius: 0.1
  md5: 2078bad371c14c36302ed0724d185dd9
- in: HGPS_Significance_0.2deg.fits.gz
  quantity: significance
  radius: 0.2
  md5: 92ee6385cb0ccd3d554d0d7f0649afb1
- in: HGPS_Flux_0.1deg.fits.gz
  quantity: flux
  radius: 0.1
  md5: cad4dc35220e75829d2882a2aa96461e
- in: HGPS_Flux_0.2deg.fits.gz
  quantity: flux
  radius: 0.2
  md5: 22fa88d4e3cfc36b2b17cd55e2237bcf
- in: HGPS_Flux_Err_0.1deg.fits.gz
  quantity: flux_err
  radius: 0.1
  md5: 17981eb64e029d60be67421815d3c549
- in: HGPS_Flux_Err_0.2deg.fits.gz
  quantity: flux_err
  radius: 0.2
  md5: f3641d7aa243a24e46e7e4cf68a9ce9b
- in: HGPS_Flux_UL_0.1deg.fits.gz
  quantity: flux_ul
  radius: 0.1
  md5: a269deaddaf6e50dbbbc8a1bd297738e
- in: HGPS_Flux_UL_0.2deg.fits.gz
  quantity: flux_ul
  radius: 0.2
  md5: 17b843d48608f3ad49b73f88bc3a7f01
- in: HGPS_Sensitivity_0.1deg.fits.gz
  quantity: sensitivity
  radius: 0.1
  md5: 53076dbde0691ae52fe50a8becb5f53c
- in: HGPS_Sensitivity_0.2deg.fits.gz
  quantity: sensitivity
  radius: 0.2
  md5: d46fe4745b10aa5029b086eebc228188

figures:
- number: 1
  paper_repo: figures/hgps_region_exposure_illustration.pdf
  analysis_repo: code/hgps/figures/hgps_region_exposure_illustration/hgps_region_exposure_illustration.pdf
  webpage_repo: hgps_region_exposure_illustration.pdf
- number: 2
  paper_repo: figures/hgps_energy_threshold_profiles.pdf
  analysis_repo: code/hgps/figures/energy_threshold/hgps_energy_threshold_profiles.pdf
  webpage_repo: hgps_energy_threshold_profiles.pdf
- number: 3
  paper_repo: figures/hgps_map_background_estimation.pdf
  analysis_repo: code/hgps/figures/exclusion_background_regions/hgps_map_background_estimation.pdf
  webpage_repo: hgps_map_background_estimation.pdf
- number: 4
  paper_repo: figures/hgps_sensitivity.pdf
  analysis_repo: code/hgps/figures/sensitivity/hgps_sensitivity.pdf
  webpage_repo: hgps_sensitivity.pdf
- number: 5
  paper_repo: figures/hgps_catalog_model.pdf
  analysis_repo: code/hgps/figures/catalog_model_illustration/hgps_catalog_model.pdf
  webpage_repo: hgps_catalog_model.pdf
- number: 6
  paper_repo: figures/hgps_diffuse_model.pdf
  analysis_repo: code/hgps/figures/diffuse_band_parameters/hgps_diffuse_model.pdf
  webpage_repo: hgps_diffuse_model.pdf
- number: 7
  paper_repo: figures/hgps_residual_distribution_ts.pdf
  analysis_repo: code/hgps/figures/map_pixel_significance_distributions/hgps_residual_significance_distribution_ts.pdf
  webpage_repo: hgps_residual_distribution_ts.pdf
- number: 8
  paper_repo: figures/hgps_spectrum_background_estimation.pdf
  analysis_repo: code/hgps/figures/exclusion_background_regions/hgps_spectrum_background_estimation.pdf
  webpage_repo: hgps_spectrum_background_estimation.pdf
- number: 9
  paper_repo: figures/hgps_sources_spectrum_map_flux_comparison.pdf
  analysis_repo: code/hgps/figures/source_parameter_distributions_spectra/hgps_sources_spectrum_map_flux_comparison.pdf
  webpage_repo: hgps_sources_spectrum_map_flux_comparison.pdf
- number: 10
  paper_repo: figures/hgps_source_id.pdf
  analysis_repo: code/hgps/figures/source_classes_pie_chart/hgps_source_id.pdf
  webpage_repo: hgps_source_id.pdf
- number: 11
  paper_repo: figures/hgps_sources_glat.pdf
  analysis_repo: code/hgps/figures/source_parameter_distributions/hgps_sources_glat.pdf
  webpage_repo: hgps_sources_glat.pdf
- number: 12
  paper_repo: figures/hgps_sources_glon.pdf
  analysis_repo: code/hgps/figures/source_parameter_distributions/hgps_sources_glon.pdf
  webpage_repo: hgps_sources_glon.pdf
- number: 13
  paper_repo: figures/hgps_sources_flux_extension.pdf
  analysis_repo: code/hgps/figures/flux_extension_scatter_plot/hgps_sources_flux_extension.pdf
  webpage_repo: hgps_sources_flux_extension.pdf
- number: 14
  paper_repo: figures/hgps_sources_spectral_index.pdf
  analysis_repo: code/hgps/figures/source_parameter_distributions/hgps_sources_spectral_index.pdf
  webpage_repo: hgps_sources_spectral_index.pdf
- number: 15
  paper_repo: figures/hgps_sources_log_n_log_s.pdf
  analysis_repo: code/hgps/figures/hgps_sources_log_n_log_s/hgps_sources_log_n_log_s.pdf
  webpage_repo: hgps_sources_log_n_log_s.pdf
- number: 16
  paper_repo: figures/hgps_face_on_milky_way.pdf
  analysis_repo: code/hgps/figures/face_on_milky_way/hgps_face_on_milky_way.pdf
  webpage_repo: hgps_face_on_milky_way.pdf
- number: 17
  paper_repo: figures/hgps_spectra_new_sources.pdf
  analysis_repo: code/hgps/figures/spectra/hgps_spectra_new_sources.pdf
  webpage_repo: hgps_spectra_new_sources.pdf
- number: 18
  paper_repo: figures/per-source-plots/HESS_J1119m614.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1119m614.pdf
  webpage_repo: HESS_J1119m614.pdf
- number: 19
  paper_repo: figures/per-source-plots/HESS_J1457m593.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1457m593.pdf
  webpage_repo: HESS_J1457m593.pdf
- number: 20
  paper_repo: figures/per-source-plots/HESS_J1458m608.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1458m608.pdf
  webpage_repo: HESS_J1458m608.pdf
- number: 21
  paper_repo: figures/per-source-plots/HESS_J1503m582.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1503m582.pdf
  webpage_repo: HESS_J1503m582.pdf
- number: 22
  paper_repo: figures/per-source-plots/HESS_J1554m550.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1554m550.pdf
  webpage_repo: HESS_J1554m550.pdf
- number: 23
  paper_repo: figures/per-source-plots/HESS_J1813m126.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1813m126.pdf
  webpage_repo: HESS_J1813m126.pdf
- number: 24
  paper_repo: figures/per-source-plots/HESS_J1826m130.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1826m130.pdf
  webpage_repo: HESS_J1826m130.pdf
- number: 25
  paper_repo: figures/per-source-plots/HESS_J1828m099.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1828m099.pdf
  webpage_repo: HESS_J1828m099.pdf
- number: 26
  paper_repo: figures/per-source-plots/HESS_J1832m085.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1832m085.pdf
  webpage_repo: HESS_J1832m085.pdf
- number: 27
  paper_repo: figures/per-source-plots/HESS_J1833m105.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1833m105.pdf
  webpage_repo: HESS_J1833m105.pdf
- number: 28
  paper_repo: figures/per-source-plots/HESS_J1843m033.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1843m033.pdf
  webpage_repo: HESS_J1843m033.pdf
- number: 29
  paper_repo: figures/per-source-plots/HESS_J1844m030.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1844m030.pdf
  webpage_repo: HESS_J1844m030.pdf
- number: 30
  paper_repo: figures/per-source-plots/HESS_J1846m029.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1846m029.pdf
  webpage_repo: HESS_J1846m029.pdf
- number: 31
  paper_repo: figures/per-source-plots/HESS_J1848m018.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1848m018.pdf
  webpage_repo: HESS_J1848m018.pdf
- number: 32
  paper_repo: figures/per-source-plots/HESS_J1849m000.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1849m000.pdf
  webpage_repo: HESS_J1849m000.pdf
- number: 33
  paper_repo: figures/per-source-plots/HESS_J1852m000.pdf
  analysis_repo: code/hgps/figures/new_sources/per-source-plots/HESS_J1852m000.pdf
  webpage_repo: HESS_J1852m000.pdf
- number: 34
  paper_repo: figures/hgps_survey_flux.pdf
  analysis_repo: code/hgps/figures/survey_flux/hgps_survey_flux.pdf
  webpage_repo: hgps_survey_flux.pdf
- number: 35
  paper_repo: figures/hgps_survey_mwl_1.pdf
  analysis_repo: code/hgps/figures/survey_large_associations/hgps_survey_mwl_1.pdf
  webpage_repo: hgps_survey_mwl_1.pdf
- number: 36
  paper_repo: figures/hgps_survey_mwl_2.pdf
  analysis_repo: code/hgps/figures/survey_large_associations/hgps_survey_mwl_2.pdf
  webpage_repo: hgps_survey_mwl_2.pdf
- number: 37
  paper_repo: figures/hgps_survey_mwl_3.pdf
  analysis_repo: code/hgps/figures/survey_large_associations/hgps_survey_mwl_3.pdf
  webpage_repo: hgps_survey_mwl_3.pdf
- number: 38
  paper_repo: figures/hgps_survey_mwl_4.pdf
  analysis_repo: code/hgps/figures/survey_large_associations/hgps_survey_mwl_4.pdf
  webpage_repo: hgps_survey_mwl_4.pdf
- number: 39
  paper_repo: figures/hgps_survey_rois.pdf
  analysis_repo: code/hgps/figures/survey_rois/hgps_survey_rois.pdf
  webpage_repo: hgps_survey_rois.pdf

figures_extra:
- filename: hgps_survey_significance_single_panel_no_axes.png
  description: Significance, single-panel, no sky image axes
- filename: hgps_survey_significance_single_panel.png
  description: Significance, single-panel, with sky image axes
- filename: hgps_survey_significance_four_panel.png
  description: Significance, four-panel, with sky image axes
- filename: hgps_survey_flux_single_panel_no_axes.png
  description: Flux, single-panel, no sky image axes
- filename: hgps_survey_flux_single_panel.png
  description: Flux, single-panel, with sky image axes
- filename: hgps_survey_flux_four_panel.png
  description: Flux, four-panel, with sky image axes
